apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-BUILDNO
  labels:
    app: roboshop
    tier: payment
    build: "BUILDNO"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: payment
      build: "BUILDNO"
  template:
    metadata:
      labels:
        tier: payment
        build: "BUILDNO"
    spec:
      containers:
        - name: payment
          image: rkalluru/b48-payment:BUILDNO
          ports:
            - containerPort: 7005
          env:
            - name: REDIS_HOST
              value: redis
            - name: CATALOGUE_HOST
              value: catalogue
            - name: CATALOGUE_PORT
              value: "7002"
